const DirectoryActionTypes = {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
    ADD_PRODUCT: 'ADD_PRODUCT',
    FETCH_ADS_START: 'FETCH_ADS_START',
    FETCH_ADS_SUCCESS: 'FETCH_ADS_SUCCESS',
    FETCH_ADS_FAILURE: 'FETCH_ADS_FAILURE'
};

export default DirectoryActionTypes;