const DirectoryActionTypes = {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
    ADD_PRODUCT: 'ADD_PRODUCT',
    FETCH_ADS_START: 'FETCH_ADS_START',
    FETCH_ADS_SUCCESS: 'FETCH_ADS_SUCCESS',
    FETCH_ADS_FAILURE: 'FETCH_ADS_FAILURE',
    ADD_AD: 'ADD_AD',
    DELETE_AD: 'DELETE_AD',
    ADD_ORDER:'ADD_ORDER',
    ADD_CATEGORY:'ADD_CATEGORY',
    DELETE_CATEGORY:'DELETE_CATEGORY',
    UPDATE_CATEGORY:'UPDATE_CATEGORY',
    ADD_ADVERTISER:'ADD_ADVERTISER',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT'
};

export default DirectoryActionTypes;